name: cle-roboto
on:
  issues:
    types:
      - opened
  repository_dispatch:
    types:
      - clic_update
  workflow_dispatch: # allows manual triggering
    inputs:
        release_tag:
            description: 'Tag to update to'
            required: true
            default: 'master'


jobs:
  cle-roboto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: clEsperanto/cle-roboto-repo@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}